name: btcc
description: Flutter app to score castles for the game Between Two Castles 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.5+6

environment:
  sdk: ">=2.7.0 <3.0.0"

flutter_icons:
  image_path: 'assets/images/logo.png'
  android: true
  ios: true

dependencies:
  flutter:
    sdk: flutter
  tflite:
#    path: '..\..\..\OtherProjects\flutter_tflite'
    git:
      url: https://github.com/mitchhymel/flutter_tflite.git
      ref: master
  permission_handler: ^8.0.1
  path_provider: ^2.0.2
  provider: ^5.0.0
  json_annotation: ^4.0.1
  image: ^3.0.2
  exif: ^3.0.0
  file_picker: ^3.0.2+2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  auto_size_text: ^2.1.0
  firebase_core: ^1.2.1
  firebase_analytics: ^8.1.1
  firebase_crashlytics: ^2.0.5
  url_launcher: ^6.0.6
  flutter_email_sender: ^5.0.0
  camera: ^0.9.2+2
  draggable_scrollbar: ^0.1.0
  flutter_hooks: ^0.17.0
  screenshot: ^1.2.3
  image_gallery_saver: ^1.7.1

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  hive_generator: ^1.1.0
  flutter_launcher_icons: ^0.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
